# Generated by Django 5.2 on 2025-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fileinput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filedata", models.CharField(max_length=255)),
                ("tableN", models.CharField(max_length=100)),
            ],
        ),
    ]
