# Generated by Django 5.2 on 2025-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileinput",
            name="filedata",
        ),
        migrations.RemoveField(
            model_name="fileinput",
            name="tableN",
        ),
        migrations.AddField(
            model_name="fileinput",
            name="가구소득금액",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileinput",
            name="개인소득구간코드",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fileinput",
            name="개인소득금액",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fileinput",
            name="기준년월",
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name="fileinput",
            name="성별코드",
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name="fileinput",
            name="신우편번호",
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name="fileinput",
            name="연령대코드",
            field=models.IntegerField(default=0),
        ),
    ]
