# Generated by Django 5.2 on 2025-05-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fileinput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("기준년월", models.CharField(default=0, max_length=6)),
                ("신우편번호", models.CharField(default=0, max_length=5)),
                ("연령대코드", models.IntegerField(default=0)),
                ("성별코드", models.CharField(default=0, max_length=1)),
                ("개인소득구간코드", models.IntegerField(default=0)),
                ("가구소득금액", models.IntegerField(blank=True, null=True)),
                ("개인소득금액", models.IntegerField(default=0)),
            ],
        ),
    ]
