# Generated by Django 5.2 on 2025-10-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="file_DB",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                ("data_name", models.CharField(max_length=100)),
                ("data_date", models.DateField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PISafeZone.user",
                    ),
                ),
            ],
        ),
    ]
