# Generated by Django 5.2 on 2025-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PISafeZone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinput",
            name="기준년월",
            field=models.CharField(default=0, max_length=8),
        ),
    ]
