# Generated by Django 5.2.8 on 2025-11-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PISafeZone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='catalog',
            field=models.CharField(default='기타', max_length=200),
            preserve_default=False,
        ),
    ]
